# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-d2623a8c-8bae-4f5d-9d52-a87a0b6b119c";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-d2623a8c-8bae-4f5d-9d52-a87a0b6b119c".device = "/dev/disk/by-uuid/d2623a8c-8bae-4f5d-9d52-a87a0b6b119c";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-d2623a8c-8bae-4f5d-9d52-a87a0b6b119c";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-d2623a8c-8bae-4f5d-9d52-a87a0b6b119c";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1BDA-C448";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ec7d83b0-dbc5-4e46-acf3-791cccbbc4e9"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
